<a href="https://colab.research.google.com/github/Sean1686/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [6]:

import pandas as pd
import numpy as np

In [7]:

print(pd.__version__)

2.2.2

In [8]:

# Dictionary
mydataset = {
  'cars': ["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Bugatti", "BMW"],
  'counts': [3, 7, 2, 5, 8, 14, 17]
}
print(mydataset, "\n")

df = pd.DataFrame(mydataset)
print(df, "\n")

{'cars': ['BMW', 'Volvo', 'Ford', 'Tesla', 'Ferrari', 'Bugatti', 'BMW'], 'counts': [3, 7, 2, 5, 8, 14, 17]}

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       5
4  Ferrari       8
5  Bugatti      14
6      BMW      17

In [9]:
# head method
df.head(4) # default 5 rows

    cars  counts
0    BMW       3
1  Volvo       7
2   Ford       2
3  Tesla       5

In [10]:

# tail method
df.tail(2) # default 5 rows

      cars  counts
5  Bugatti      14
6      BMW      17

In [11]:
# State Property: shape, column, dtypes
a = df.shape
print("=====\n", a)

b = df.columns
print("=====\n", b)

c = df.dtypes
print("=====\n", c)

df["cars"] = df["cars"].astype("string")
d = df.dtypes
print("=====\n", d)

=====
 (7, 2)
=====
 Index(['cars', 'counts'], dtype='object')
=====
 cars      object
counts     int64
dtype: object
=====
 cars      string[python]
counts             int64
dtype: object

In [12]:
# describe method - numeric statistikani hosil qiladi!
df.describe()
# df.describe(include="all")

          counts
count   7.000000
mean    8.000000
std     5.597619
min     2.000000
25%     4.000000
50%     7.000000
75%    11.000000
max    17.000000

In [14]:

# iloc (integer location) method - kerakli malumotlarini tanlab olish

print("=====\n", df.iloc[0])

print("=====\n", df.iloc[1])

print("=====\n", df.iloc[1,0]) # [row location, column location]

print("\n")

df.iloc[1:4]

=====
 cars      BMW
counts      3
Name: 0, dtype: object
=====
 cars      Volvo
counts        7
Name: 1, dtype: object
=====
 Volvo

    cars  counts
1  Volvo       7
2   Ford       2
3  Tesla       5

In [15]:
# loc method - kerakli malumotlarni ma'lum bir columndan tanlab olish
df.loc[1:4, "cars"]

1      Volvo
2       Ford
3      Tesla
4    Ferrari
Name: cars, dtype: string

In [16]:

print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       5
4  Ferrari       8
5  Bugatti      14
6      BMW      17

In [17]:
df["counts"] >= 3

0     True
1     True
2    False
3     True
4     True
5     True
6     True
Name: counts, dtype: bool

In [18]:
df[df["counts"] >= 3]
# df[df["cars"] == "BMW"]

      cars  counts
0      BMW       3
1    Volvo       7
3    Tesla       5
4  Ferrari       8
5  Bugatti      14
6      BMW      17

In [19]:
# mean topish
a = df.mean(numeric_only=True)
b = df["counts"].mean()

print(a, "\n")
print(b, "\n")

print("======\n")
print(df.min())

print("======\n")
print(df.max())

print("======\n")
print(df.median(numeric_only=True))

print("======\n")
print(df.count()) # None value bolmaganlarni chiqarib beradi

counts    8.0
dtype: float64

8.0

======

cars      BMW
counts      2
dtype: object
======

cars      Volvo
counts       17
dtype: object
======

counts    7.0
dtype: float64
======

cars      7
counts    7
dtype: int64

/tmp/ipykernel_7675/2593260365.py:9: FutureWarning: <class 'pandas.core.arrays.string_.StringArray'>._reduce will require a `keepdims` parameter in the future
  print(df.min())
/tmp/ipykernel_7675/2593260365.py:12: FutureWarning: <class 'pandas.core.arrays.string_.StringArray'>._reduce will require a `keepdims` parameter in the future
  print(df.max())

In [20]:

df.std(numeric_only=True)

counts    5.597619
dtype: float64

In [21]:

dataset = {
  'cars': ["BMW", "Volvo", "Ford", None, "Ferrari", "Bugatti", None],
  'counts': [3, 7, 2, None, 8, 14, 17]
}

df_missing = pd.DataFrame(dataset)
print(df_missing, "\n")

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     Ford     2.0
3     None     NaN
4  Ferrari     8.0
5  Bugatti    14.0
6     None    17.0

In [22]:
  # None nisbattan tekshiramiz
df_missing.isnull()

    cars  counts
0  False   False
1  False   False
2  False   False
3   True    True
4  False   False
5  False   False
6   True   False

In [23]:
# None holatdagi malumotlarni aniqlaymiz
df_missing.isnull().sum()

cars      2
counts    1
dtype: int64

In [24]:
# dropna method - Missing malumotlardan tozalaymiz

df_clean = df_missing.dropna()
print(df_clean)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     Ford     2.0
4  Ferrari     8.0
5  Bugatti    14.0

In [25]:
# df_missing.dropna(how="all") # har ikkalasi None bolganini ochiradi
df_missing.dropna(axis=0) # tanlangan 0-row 1-column None boyicha ochiradi
# df_missing.dropna(subset="counts") # tanlangan column None tozalaydi

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     Ford     2.0
4  Ferrari     8.0
5  Bugatti    14.0

In [26]:
# fillna method - ma'lumotlarni tog'irlab toldirib olish

# df_missing.fillna("unknown")
df_missing.fillna({"cars": "unknown", "counts": 0})

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     Ford     2.0
3  unknown     0.0
4  Ferrari     8.0
5  Bugatti    14.0
6  unknown    17.0

In [28]:
import pandas as pd

# 1D AQLLI VEKTOR
pd.Series(["BMW", "Tesla", "Bugatti"])

0        BMW
1      Tesla
2    Bugatti
dtype: object

In [29]:
# 2D TABLE MATRIX
pd.DataFrame(["BMW", "Tesla", "Bugatti"])

         0
0      BMW
1    Tesla
2  Bugatti